[tool.poetry]
name = "repl_python3_beta_RoboHacks"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
joblib = "^1.0.1"
pandas = "^1.3.1"
sklearn = "^0.0"
bs4 = "^0.0.1"
requests-html = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
